### ISSUE TITLE
Seems to not work on PyCharm

### ISSUE THREAD

**Issue by Hamster-lord** [arda-guler/HaritaWars#1]

**Comment by Hamster-lord** [comment]
Why doesn't it work for pycharm

**Comment by arda-guler** [comment]
It does.

**Comment by Hamster-lord** [comment]
for what version?

**Comment by Hamster-lord** [comment]
i get this in python 3.8

**Comment by Hamster-lord** [comment]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keyboard/__init__.py", line 294, in listen
    _os_keyboard.listen(self.direct_callback)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/keyboard/_darwinkeyboard.py", line 430, in listen
    raise OSError("Error 13 - Must be run as administrator")
OSError: Error 13 - Must be run as administrator

**Comment by arda-guler** [comment]
PyCharm 2022.3.1 Community Edition with Python 3.10 works. I don't use pycharm myself, I just installed it to check whether it works, and it did.

What I get from the error is that 'keyboard' package expects to be run as administrator.

**Comment by Hamster-lord** [comment]
It still doen't work for me

**Comment by Hamster-lord** [comment]
do you use mac or windows?

**Comment by Hamster-lord** [comment]
it works now
